### ISSUE TITLE
appimage worked only once

### ISSUE THREAD

**Issue by camillaMay** [ichi-rika/speech-analysis#14]
Hello, 

I'm on Kubuntu 20.04, I have been succesfully running the released appimage , it worked perfectly nice, but after closing the windows, and trying to start again, it won't work anymore. I didn't change anything to the system in between.

 I'm getting the following : 

Audio::Resampler] Created 48000 --> 8000
Audio::Resampler] Created 32000 --> 48000
Backtrace captured using UNWIND_BACKTRACE_WITH_SKIPPING_METHOD:
  #00:  0x18b08c  
  #01:  0x134c15  Module::Audio::Alsa::refreshDevices()
  #02:  0xd7274  Main::ContextManager::initialize()
  #03:  0xd4423  main
  #04:  0x270b3  __libc_start_main
  #05:  0xd4f91

I tried to find where the appimage stores its settings, with the hope that by deleting configuration files it would start afresh, but I don't find anything, neither in my ~.config/ or ~.<anything...>

Would you have an idea about how to troubleshoot this ?
Thank you ! 
and , thank you for the really nice program, too !

**Comment by clo-yunhee** [comment]
Hey, thanks for reporting the issue!
Version 2.1.6 of InFormant does not store any settings, so this is strange...
What's your audio setup like? ALSA->PulseAudio?
If so, have you tried killing the PulseAudio daemon and restarting it? 
It would also help if you could share a more detailed backtrace than the one generated by the program by running it through gdb or lldb. ^^

**Comment by camillaMay** [comment]
Hi ty for your quick reply !

The setup is indeed ALSA->PulseAudio - that is, the ubuntu install default.
I tried restarting pulse, and also rebooted, with no avail.

So gdb says : 

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 7219]
process 7211 is executing new program: /tmp/.mount_speechHeGbYt/AppRun
process 7211 is executing new program: /tmp/.mount_speechHeGbYt/usr/bin/speech-analysis
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Audio::Resampler] Created 48000 --> 8000
Audio::Resampler] Created 32000 --> 48000
[New Thread 0x7ffff556d700 (LWP 7224)]
[New Thread 0x7ffff4d6c700 (LWP 7225)]

Thread 1 "speech-analysis" received signal SIGSEGV, Segmentation fault.
__strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
57      ../sysdeps/x86_64/multiarch/strchr-avx2.S: No such file or directory.

Not sure how to interpret the ../ here. I have almost no clue about appimages ^_^;

**Comment by clo-yunhee** [comment]
Cool! Can you type `bt` and then the Enter key, once you get to the seg fault in gdb?

**Comment by camillaMay** [comment]
sure,

(gdb) bt
#0  __strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
#1  0x0000000000534c15 in Module::Audio::Alsa::refreshDevices() ()
#2  0x00000000004d7274 in Main::ContextManager::initialize() ()
#3  0x00000000004d4423 in main ()
(gdb)

**Comment by clo-yunhee** [comment]
Huh, that's weird

**Comment by clo-yunhee** [comment]
Hey! Can you try the newly released 3.0.1 version?

**Comment by camillaMay** [comment]
Hi !

v3.0.1 works out of the box like a charm, and many times in a row.
Amazing ! It is really great to have formant tracks , really helpful as I am working on my voice.
Thank you so so much for your diligent and nice help.

^^

**Comment by clo-yunhee** [comment]
You're very welcome! <3
