### ISSUE TITLE
Freezing and crashing within 10 seconds of launch

### ISSUE THREAD

**Issue by L-shoe** [ichi-rika/speech-analysis#15]
Hello, I'm on a Windows 10 Home 64-bit using the Windows x86 release of InFormat (3.0.0), and about 10 seconds after launch the program crashses. The program is also unresponsive to input during this time.

Here's my console output:

C:\Users\[username]\Documents\Voice\InFormant-3.0.0> .\InFormant-3.0.0.exe
Reading configuration from: "C:\\Users\\[username]\\AppData\\Roaming\\informant.ini"
Config not found, using defaults...
Audio::Resampler#2] Created 48000 --> 48000
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/stop.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/menu.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/stop.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/stop.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/stop.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/stop.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/menu.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/menu.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/menu.svg: Unsupported image format
file:///C:/Users/[username]/Documents/Voice/InFormant-3.0.0/QtQuick/Controls.2/Material/ToolButton.qml: QML IconImage: Error decoding: qrc:/icons/menu.svg: Unsupported image format
Audio::Buffer#0] Sample rate changed, might cause jank for the next few frames.
Audio::Resampler#0] Created 48000 --> 44100
Audio::Buffer#1] Sample rate changed, might cause jank for the next few frames.
Audio::Buffer#2] Sample rate changed, might cause jank for the next few frames.
Audio::Buffer#3] Sample rate changed, might cause jank for the next few frames.
Audio::Resampler#1] Created 44100 --> 12000
Audio::Resampler#3] Created 44100 --> 16000
Audio::Resampler#4] Created 44100 --> 10000
Processing fast enough, adjusted block size to 384 samples
QImage::scaled: Image is a null image
Processing fast enough, adjusted block size to 256 samples
Processing fast enough, adjusted block size to Audio::Queue] Not enough data to pull. Adjusted block duration to 128 samples
50.25 ms
Audio::Queue] Not enough data to pull. Adjusted block duration to 50.5 ms
Audio::Queue] Not enough data to pull. Adjusted block duration to Processing fast enough, adjusted block size to 050.75 samples
 ms
Processing fast enough, adjusted block size to -128 samples
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
Audio::Queue] Not enough data to pull. Adjusted block duration to 51 ms
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by clo-yunhee** [comment]
Thanks for the report, I'm pushing a hot-fix release as soon as possible ^^

**Comment by clo-yunhee** [comment]
That specific crash should be fixed with the newly released 3.0.1 version!
