### ISSUE TITLE
Icons are invisible on macOS

### ISSUE THREAD

**Issue by just-chillin** [ichi-rika/speech-analysis#18]
![image](https://user-images.githubusercontent.com/6798352/110230049-f8ada800-7edb-11eb-8aa5-dc6ce7ca5dbc.png)

Each of the icons are invisible.
I am running version 3.0.2 and have the program installed in /Applications.

Here are the relevant specs:
  System Version:	macOS 11.2.2 (20D80)
  Kernel Version:	Darwin 20.3.0
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Quad-Core Intel Core i5

**Comment by clo-yunhee** [comment]
Thanks for the report I will get to it soon

**Comment by just-chillin** [comment]
Cool! Let me know what the problem was when you figure it out!

**Comment by ellieayla** [comment]
Same symptom (no icons, oscilloscope + synthesizer buttons visible), though on;

InFormant Version: 3.0.3
System Version: macOS 11.2.3 (20D91)
Kernel Version: Darwin 20.3.0
Model Name: MacBook Pro
Model Identifier: MacBookPro17,1
Processor Name: Apple M1

**Comment by clo-yunhee** [comment]
This should have fixed the icons being invisible https://github.com/clo-yunhee/in-formant/releases/tag/3.1.1

**Comment by ellieayla** [comment]
Icons are visible in 3.1.1
