### ISSUE TITLE
In-Formant v3.x and up crashing on start

### ISSUE THREAD

**Issue by hobothulhu** [ichi-rika/speech-analysis#24]
Hello!

I am experiencing a reproducible issue where In-Formant always crashes on open. I have noted down all of the details I could think of which might be relevant. I work in software QA, so I am happy to try any suggestions you may have, if you have time. I have also attached a TXT file with the full Windows crash reports for 23 crashes of releases under v3.x

Issue:
	All releases of app for version 3.0.0 and up, for x86, x64, and MSVC, crash on startup

Hardware:
	Intel Core i7-7700k @4.2 GHz
	64 GB RAM
OS details:
	Windows 10 Pro 64-bit
	Version 21H1, OS Build 19043.1055, Windows Features Experience Pack 120.2212.2020.0
Versions Tried:
	1.3 - No crashes
	2.1 - No crashes
	2.1.1 - No crashes
	3.0.0 - Crashes on startup with both x86 and x64 releases
		Logs - x86/x64 versions
			Reading configuration from: "C:\\Users\\antioch\\AppData\\Roaming\\informant.ini"
			Config not found, using defaults...
			Audio::Resampler#2] Created 48000 --> 48000
			
			Assertion failed: FALSE, file ../src/hostapi/wdmks/pa_win_wdmks.c, line 1061
			
			Faulting application name: InFormant-3.0.0.exe, version: 0.0.0.0, time stamp: 0x603c0c4d
			Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
			Exception code: 0x40000015
			Fault offset: 0x000000000002bbc5
	3.0.3 - Crashes on startup with both x86 and x64 releases
		Logs - x86/x64 versions
			Reading configuration from: "C:\\Users\\antioch\\AppData\\Roaming\\informant.ini"
			Config not found, using defaults...
			Audio::Resampler#2] Created 48000 --> 48000
			
			Faulting application name: InFormant-3.0.3.exe, version: 0.0.0.0, time stamp: 0x6048824c
			Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
			Exception code: 0x40000015
			Fault offset: 0x000000000002bbc5
	3.0.4 - Crashes on startup with x86, x64, and MSVC releases
		Logs
			MSVC version - Crashes on open, no logs or errors generated
		x86/x64 versions - 
			---------------------------
			Microsoft Visual C++ Runtime Library
			---------------------------
			Assertion failed!

			Program: ...
			File: ../src/hostapi/wdmks/pa_win_wdmks.c
			Line: 1061

			Expression: FALSE

			For information on how your program can cause an assertion
			failure, see the Visual C++ documentation on asserts

			(Press Retry to debug the application - JIT must be enabled)
			---------------------------
			Abort   Retry   Ignore   
			---------------------------
			
			Faulting application name: InFormant-3.0.4-dev.exe, version: 0.0.0.0, time stamp: 0x60a2cb69
			Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x7f567a50
			Exception code: 0x80000003
			Fault offset: 0x00057fd0
			
			Faulting application name: InFormant-3.0.4-dev.exe, version: 0.0.0.0, time stamp: 0x60a2cb67
			Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
			Exception code: 0x80000003
			Fault offset: 0x00000000000c9142
			
			Faulting application name: InFormant-3.0.4-dev.exe, version: 0.0.0.0, time stamp: 0x60a2cb67
			Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x5e7863c4
			Exception code: 0x40000015
			Fault offset: 0x00000000000206ca
			
Troubleshooting steps taken:
	Running app as Administrator
	Running on a clean boot, no startup applications
	Troubleshooting Compatibility for Windows 8
	Using the 'app.exe >> log.txt' startup switch to capture logs
Versions that work:
	Any release before 3.x
[informant_reports.txt](https://github.com/clo-yunhee/in-formant/files/6687955/informant_reports.txt)

**Comment by clo-yunhee** [comment]
Thank you for the very detailed report! Does the 3.1 version still have that issue?

**Comment by hobothulhu** [comment]
I'm very happy to report that the 3.1 version opens for me! Thank you very much for your work!
