### ISSUE TITLE
Can't install on OS X with homebrewed dependencies

### ISSUE THREAD

**Issue by autumnsault** [ichi-rika/speech-analysis#3]
I tried running the Mac build script, and that error'd. Then I tried doing the normal cmake thing, creating a build directory. That got a lot further, but it failed with some errors that make me think it's not finding my local install of qt5 (but rather using its own). According to Homebrew, there are some cmake problems with qt5 on OS X.

```
Note: Using static linking will disable the use of dynamically
loaded plugins. Make sure to import all needed static plugins,
or compile needed modules into the library.

ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && features.xkbcommon && libs.xcb' failed.

Check config.log for details.
make[2]: *** [qt5/src/qt5-stamp/qt5-configure] Error 3
make[1]: *** [CMakeFiles/qt5.dir/all] Error 2
make: *** [all] Error 2
```
There are the final errors.

It looks like there's no way to tell it where to look for the existing qt5 install in the cmake configuration, unless I'm missing something.

Any help would be appreciated. Thanks for creating this. :)

**Comment by mohawkjohn** [comment]
Okay, so I figured it out.

I had to use my homebrew version of Qt5, which required me to comment out the `ExternalProject_Add` line for qt5 (root `CMakeLists.txt`), remove it from the `add_dependencies` line at the bottom of the file, and then to add a line to the `src/CMakeLists.txt` file with my Qt5 path information:

```
set(Qt5_DIR /usr/local/Cellar/qt/5.14.0/lib/cmake/Qt5)
```

Also, the flag `ext-numeric-literals` is a gcc option which doesn't apply to clang, so I removed that. With these changes, it compiles and runs! Hooray!

**Comment by ichi-rika** [comment]
Yay! Yeah, the plan was to compile its own version of Qt to link it
statically, so that there wouldn't be any dependencies issues for people
just downloading and running it. It's probably unrealistic though.

**Comment by autumnsault** [comment]
For others wanting to see what I did, I went ahead and pushed my changes. They definitely aren't very portable, so I didn't send a pull request.

https://github.com/autumnsault/speech-analysis/tree/mac

**Comment by ichi-rika** [comment]
Update on this, the build process now uses Docker. I've been working on and off on getting a Linux to OSX crosscompiler working, no promises though.
